#Alpine is base image and cloning web application from git hub
FROM alpine/git as gitclone
WORKDIR /app
RUN git clone https://github.com/MithunTechnologiesDevOps/maven-web-application.git

#maven image build code using maven tool
FROM maven:3.8-eclipse-temurin-11 as mvnbuild
WORKDIR /app
COPY --from=gitclone /app/maven-web-application/ ./
RUN mvn package

#tomcat image and copy .war into webapps directory
FROM tomcat:8.5.78-jre8-temurin-focal
COPY --from=mvnbuild /app/target/*.war  /usr/local/tomcat/webapps
EXPOSE 8086